### ISSUE TITLE
Add id-Tag for each line (and maybe even relation)

### ISSUE THREAD

**Issue by nw520** [osm-ToniE/ptna#73]
Hello!

I'd like to suggest to add an id-tag to every public transport line listed in the generated HTML-file. This would allow one to directly link to a public transport line in the form of https://ptna.openstreetmap.de/results/DE/SL/DE-SL-saarVV-Analysis.html#bus_150 rather than only to a section, which can be quite handy for wiki articles.

The generated HTML would look something like: `<tr id="bus_101" data-info="..." data-ref="101" class="sketchline">`

Cheers

**Comment by osm-ToniE** [comment]
Right, good idea.

I would apply this to the "Sketchline" only, as you suggest.

Problem could appear if there are two lines with same type and ref:

DE-NW-VRS:

N8;bus;Existiert zweimal im VRS: Hier Bonn - Oberkassel;Bonn Hbf;Bonn Hbf;SWB
N8;bus;Existiert zweimal im VRS: Hier Leichlingen;Leichlingen Bf;Kleine Heide;Wiedenhoff

Not a big issue in this case, because they appear directly one after the other.

But for DE-SN-VMS

A;bus;;;;
B;bus;;;;
...

some busses appear up to 7 times at different locations in the report.

**Comment by osm-ToniE** [comment]
Solution:

add: id="bus_A" for "sketchline" line for Bus A
add: id="bus_A-2" for "sketchline" line if the same bus appears a second time (maybe same bus, maybe a different bus in different village/city with same 'ref')
add: id="bus_A-3" for "sketchline" line if the same bus appears a third time, and so on

add: id="<relation-id>" in other lines, for the first appearance of this Route-Master/Route-Relation
don't add same relation-id as 'id' a second time - does not provide additional information

Remark:

id="..." must only consist of 0-9, A-Z, a-z, '_', '-' and '.'. (HTML standard).
All other characters will be replaced by '_', multiple successive appearance of '_' may occur (e.g. 
84(X)/85/88(X);bus;;;; 
will appear
id="bus_84_X__85_88_X_
